Repository getsentry/sentry-dotnet, pull requests merged in 2021-04, with the labels that each got.

#911 Don't serialize `IsSampled` for Transaction (Contexts.Trace) and Span
  src/Sentry/Protocol/Trace.cs
  src/Sentry/Span.cs
  test/Sentry.Tests/Protocol/Context/TraceTests.cs
Labels: Performance Product

#918 Fix references to removed code from configuration
  samples/Sentry.Samples.AspNetCore5.Mvc/appsettings.json
Labels: ASP.NET Core, samples

#922 Inherit TraceId from transaction in spans
  CHANGELOG.md
  src/Sentry/SpanTracer.cs
  src/Sentry/TransactionTracer.cs
  test/Sentry.Tests/Protocol/TransactionTests.cs
Labels: Performance Product, bug

#908 Limit max spans in transaction to 1000
  CHANGELOG.md
  src/Sentry/Internal/Hub.cs
  src/Sentry/TransactionTracer.cs
  test/Sentry.Tests/HubTests.cs
  test/Sentry.Tests/Protocol/TransactionTests.cs
Labels: Performance Product

#923 Drop unfinished spans from transaction
  CHANGELOG.md
  src/Sentry/Transaction.cs
  test/Sentry.Tests/Internals/Http/CachingTransportTests.cs
  test/Sentry.Tests/Protocol/TransactionTests.cs
Labels: Performance Product

#924 Move Description field from Transaction to Trace context
  CHANGELOG.md
  src/Sentry/ISpanContext.cs
  src/Sentry/Protocol/ITraceContext.cs
  src/Sentry/Protocol/Trace.cs
  src/Sentry/Transaction.cs
Labels: Performance Product, bug

#928 Don't override Span/Transaction status on Finish(...) if status was not provided explicitly
  CHANGELOG.md
  src/Sentry/ISpan.cs
  src/Sentry/SpanTracer.cs
  src/Sentry/TransactionTracer.cs
  test/Sentry.Tests/HubTests.cs
  test/Sentry.Tests/Internals/Http/CachingTransportTests.cs
  test/Sentry.Tests/Protocol/TransactionTests.cs
Labels: Performance Product, bug

#942 Temporarily disable parallelization
  test/xunit.runner.json
Labels: Repository maintenance
