Repository getsentry/sentry-dotnet, pull requests merged in 2021-07, with the labels that each got.

#1113 Add HTTP request breadcrumb
  CHANGELOG.md
  src/Sentry/SentryHttpMessageHandler.cs
  test/Sentry.Tests/SentryHttpMessageHandlerTests.cs
Labels: enhancement

#1101 Avoid Unhandled Exception on .NET 461 if the Registry Access threw an exception.
  samples/Sentry.Samples.Console.Basic/Sentry.Samples.Console.Basic.csproj
  src/Sentry/Integrations/NetFxInstallationsIntegration.cs
  src/Sentry/PlatformAbstractions/FrameworkInfo.NetFx.cs
  src/Sentry/PlatformAbstractions/Runtime.cs
  src/Sentry/PlatformAbstractions/RuntimeInfo.cs
  src/Sentry/SentryOptions.cs
Labels: bug

#1117 Full debug logging for Sentry in ASP.NET Core sample
  samples/Sentry.Samples.AspNetCore5.Mvc/appsettings.json
Labels: Repository maintenance

#1123 TryRecoverPersistedSession logs debug if file doesnt exist
  CHANGELOG.md
  src/Sentry/GlobalSessionManager.cs
Labels: Release Health

#1125 Persisted Sessions logging
  CHANGELOG.md
  src/Sentry/GlobalSessionManager.cs
  test/Sentry.Tests/GlobalSessionManagerTests.cs
Labels: enhancement

#1124 Introduce scope stack abstraction
  CHANGELOG.md
  src/Sentry.AspNet/Internal/HttpContextScopeStackContainer.cs
  src/Sentry.AspNet/SentryAspNetOptionsExtensions.cs
  src/Sentry/Internal/Hub.cs
  src/Sentry/Internal/ScopeStack/AsyncLocalScopeStackContainer.cs
  src/Sentry/Internal/ScopeStack/GlobalScopeStackContainer.cs
  src/Sentry/Internal/ScopeStack/IScopeStackContainer.cs
  src/Sentry/Internal/SentryScopeManager.cs
  src/Sentry/SentryOptions.cs
  test/Sentry.Tests/Internals/ScopeStack/AsyncLocalScopeStackContainerTests.cs
  test/Sentry.Tests/Internals/ScopeStack/GlobalScopeStackContainerTests.cs
  test/Sentry.Tests/Internals/SentryScopeManagerTests.cs
  test/Sentry.Tests/SentryOptionsTests.cs
  test/Sentry.Tests/SentrySdkTests.cs
Labels: ASP.NET, Unity, WPF, WinForms, Xamarin, desktop

#1139 Don't cancel cache flushing on init
  CHANGELOG.md
  src/Sentry/Internal/SdkComposer.cs
Labels: Offline Caching, enhancement

#1134 Fix: Avoid serializing dangerous types.
  CHANGELOG.md
  src/Sentry.Extensions.Logging/SentryLoggerProvider.cs
  src/Sentry/Internal/Extensions/JsonExtensions.cs
  src/Sentry/Internal/SentryJsonConverter.cs
  test/Sentry.Tests/Internals/JsonTests.cs
Labels: bug
