Repository getsentry/sentry-dotnet, pull requests merged in 2021-06, with the labels that each got.

#1037 Finish span with exception in SentryHttpMessageHandler
  CHANGELOG.md
  src/Sentry/SentryHttpMessageHandler.cs
  test/Sentry.Tests/SentryHttpMessageHandlerTests.cs
Labels: Performance Product

#1039 Attempt to fix danger
  dangerfile.js
Labels: Repository maintenance

#1059 Revert changes to dangerfile.js
  dangerfile.js
Labels: Repository maintenance

#1048 Make debug diagnostic logger obsolete and add Trace diagnostic logger.
  CHANGELOG.md
  src/Sentry.AspNet/SentryAspNetOptionsExtensions.cs
  src/Sentry/Infrastructure/DebugDiagnosticLogger.cs
  src/Sentry/Infrastructure/TraceDiagnosticLogger.cs
Labels: enhancement

#1064 Add System.Reflection.Metadata as a dependency for netcoreapp3.0 target
  CHANGELOG.md
  Directory.Build.props
  src/Sentry/Sentry.csproj
Labels: bug

#1060 Refactor JSON serialization
  src/Sentry/Breadcrumb.cs
  src/Sentry/Envelopes/Envelope.cs
  src/Sentry/Envelopes/EnvelopeItem.cs
  src/Sentry/Exceptions/Mechanism.cs
  src/Sentry/Exceptions/SentryException.cs
  src/Sentry/Exceptions/SentryStackFrame.cs
  src/Sentry/Exceptions/SentryStackTrace.cs
  src/Sentry/IJsonSerializable.cs
  src/Sentry/Internal/Extensions/CollectionsExtensions.cs
  src/Sentry/Internal/Extensions/JsonExtensions.cs
  src/Sentry/Internal/Extensions/MiscExtensions.cs
  src/Sentry/Package.cs
  src/Sentry/Protocol/App.cs
  src/Sentry/Protocol/Browser.cs
  src/Sentry/Protocol/Contexts.cs
  src/Sentry/Protocol/Device.cs
  src/Sentry/Protocol/Gpu.cs
  src/Sentry/Protocol/OperatingSystem.cs
  src/Sentry/Protocol/Runtime.cs
  src/Sentry/Protocol/Trace.cs
  src/Sentry/Request.cs
  src/Sentry/SdkVersion.cs
  src/Sentry/SentryEvent.cs
  src/Sentry/SentryMessage.cs
  src/Sentry/SentryThread.cs
  src/Sentry/SentryValues.cs
  src/Sentry/SessionUpdate.cs
  src/Sentry/Span.cs
  src/Sentry/Transaction.cs
  src/Sentry/User.cs
  src/Sentry/UserFeedback.cs
  test/Sentry.Tests/Helpers/JsonSerializableExtensions.cs
Labels: Repository maintenance

#1068 Add auto session tracking
  CHANGELOG.md
  src/Sentry/Integrations/AutoSessionTrackingIntegration.cs
  src/Sentry/SentryOptions.cs
Labels: Release Health, enhancement

#1069 Implement pause & resume session
  CHANGELOG.md
  src/Sentry/Extensibility/DisabledHub.cs
  src/Sentry/Extensibility/HubAdapter.cs
  src/Sentry/GlobalSessionManager.cs
  src/Sentry/IHub.cs
  src/Sentry/ISession.cs
  src/Sentry/ISessionManager.cs
  src/Sentry/Internal/Hub.cs
  src/Sentry/SentryOptions.cs
  src/Sentry/SentrySdk.cs
  src/Sentry/Session.cs
  src/Sentry/SessionUpdate.cs
  test/Sentry.Tests/GlobalSessionManagerTests.cs
  test/Sentry.Tests/HubTests.cs
  test/Sentry.Tests/Internals/Http/HttpTransportTests.cs
  test/Sentry.Tests/Protocol/Envelopes/EnvelopeTests.cs
  test/Sentry.Tests/SessionTests.cs
Labels: Release Health

#1082 Add tests for session pause/resume and auto tracking
  src/Sentry/SentryOptions.cs
  test/Sentry.Tests/GlobalSessionManagerTests.cs
  test/Sentry.Tests/HubTests.cs
Labels: Repository maintenance

#1084 Add SDK information to envelope
  CHANGELOG.md
  src/Sentry/Envelopes/Envelope.cs
  src/Sentry/Internal/Empty.cs
  src/Sentry/Internal/Enricher.cs
  src/Sentry/SdkVersion.cs
  test/Sentry.Tests/PlatformAbstractions/RuntimeInfoTests.cs
  test/Sentry.Tests/Protocol/Envelopes/EnvelopeTests.cs
Labels: Performance Product

#1089 IHub.ResumeSession(): don't start a new session if pause wasn't called or if there is no active session
  CHANGELOG.md
  src/Sentry/GlobalSessionManager.cs
  src/Sentry/ISessionManager.cs
  src/Sentry/Internal/Hub.cs
  test/Sentry.Tests/HubTests.cs
Labels: Release Health

#1094 fix: incorrect order when getting the last active span.
  CHANGELOG.md
  src/Sentry/TransactionTracer.cs
Labels: Performance Product, bug
