Repository getsentry/sentry-dotnet, pull requests merged in 2021-03, with the labels that each got.

#871 Fix CachingTransport throwing an exception can't move the files
  CHANGELOG.md
  src/Sentry/Internal/Http/CachingTransport.cs
Labels: Xamarin, bug

#877 Don't add version prefix in release if it's already set
  CHANGELOG.md
  src/Sentry/Internal/ApplicationVersionLocator.cs
  src/Sentry/Internal/Polyfills.cs
  test/Sentry.Tests/Internals/ApplicationVersionLocatorTests.cs
Labels: enhancement

#875 Enrich transactions with more data
  CHANGELOG.md
  samples/Sentry.Samples.AspNetCore5.Mvc/Startup.cs
  samples/Sentry.Samples.AspNetCore5.Mvc/appsettings.json
  src/Sentry.AspNetCore/SentryTracingMiddleware.cs
  src/Sentry/Internal/Enricher.cs
  src/Sentry/Internal/Hub.cs
  src/Sentry/Internal/MainSentryEventProcessor.cs
  src/Sentry/SentryOptionsExtensions.cs
  test/Sentry.AspNetCore.Tests/SentryTracingMiddlewareTests.cs
  test/Sentry.Tests/HubTests.cs
  test/Sentry.Tests/Internals/MainSentryEventProcessorTests.cs
Labels: Performance Product, enhancement

#884 Retrieve CurrentVersion for Asp Net applications.
  CHANGELOG.md
  src/Sentry.AspNet/Internal/SystemWebVersionLocator.cs
  src/Sentry.AspNet/SentryAspNetOptionsExtensions.cs
  test/Sentry.AspNet.Tests/Internal/SystemWebVersionLocatorTests.cs
Labels: enhancement

#885 Add IsParentSampled to TransactionContext
  CHANGELOG.md
  src/Sentry/HubExtensions.cs
  src/Sentry/Internal/Hub.cs
  src/Sentry/Internal/SynchronizedRandom.cs
  src/Sentry/SentryClient.cs
  src/Sentry/SentryOptions.cs
  src/Sentry/TransactionContext.cs
  test/Sentry.Tests/HubTests.cs
Labels: Performance Product

#880 Rework transactions
  CHANGELOG.md
  src/Sentry/Dsn.cs
  src/Sentry/Envelopes/Envelope.cs
  src/Sentry/Envelopes/EnvelopeItem.cs
  src/Sentry/Exceptions/SentryStackFrame.cs
  src/Sentry/Extensibility/DisabledHub.cs
  src/Sentry/Extensibility/HubAdapter.cs
  src/Sentry/Extensibility/ISentryStackTraceFactory.cs
  src/Sentry/Extensibility/SentryStackTraceFactory.cs
  src/Sentry/HubExtensions.cs
  src/Sentry/IHasBreadcrumbs.cs
  src/Sentry/ISentryClient.cs
  src/Sentry/ISpan.cs
  src/Sentry/ISpanData.cs
  src/Sentry/ITransaction.cs
  src/Sentry/ITransactionData.cs
  src/Sentry/Internal/Extensions/JsonExtensions.cs
  src/Sentry/Internal/Hub.cs
  src/Sentry/Internal/MonoSentryStackTraceFactory.cs
  src/Sentry/Reflection/AssemblyExtensions.cs
  src/Sentry/Scope.cs
  src/Sentry/ScopeExtensions.cs
  src/Sentry/SentryClient.cs
  src/Sentry/SentryOptions.cs
  src/Sentry/SentrySdk.cs
  src/Sentry/Span.cs
  src/Sentry/SpanTracer.cs
  src/Sentry/Transaction.cs
  src/Sentry/TransactionTracer.cs
  test/Sentry.AspNetCore.Tests/SentryMiddlewareTests.cs
  test/Sentry.AspNetCore.Tests/SentryTracingMiddlewareTests.cs
  test/Sentry.Tests/HubTests.cs
  test/Sentry.Tests/Protocol/TransactionTests.cs
  test/Sentry.Tests/ScopeTests.cs
  test/Sentry.Tests/SentryClientTests.cs
  test/Sentry.Tests/SentryHttpMessageHandlerTests.cs
Labels: Performance Product

#901 Add Platform to Transaction, mimicking the same property on SentryEvent
  CHANGELOG.md
  src/Sentry/IEventLike.cs
  src/Sentry/Internal/Enricher.cs
  src/Sentry/Internal/MainSentryEventProcessor.cs
  src/Sentry/Scope.cs
  src/Sentry/SentryEvent.cs
  src/Sentry/Transaction.cs
  src/Sentry/TransactionTracer.cs
Labels: Performance Product

#900 Make description parameter nullable on StartChild(...)
  CHANGELOG.md
  src/Sentry/HubExtensions.cs
  src/Sentry/ISpan.cs
  src/Sentry/SentrySdk.cs
  src/Sentry/TransactionContext.cs
Labels: Performance Product

#887 Add StartupTime and Device.BootTime
  CHANGELOG.md
  src/Sentry/Internal/Enricher.cs
  src/Sentry/Internal/ProcessInfo.cs
  src/Sentry/SentryOptions.cs
  src/Sentry/SentrySdk.cs
  test/Sentry.Testing/FuncExtensions.cs
  test/Sentry.Tests/Internals/ProcessInfoTests.cs
  test/Sentry.Tests/SentryOptionsExtensionsTests.cs
Labels: enhancement

#909 Link events to active span
  CHANGELOG.md
  src/Sentry/Internal/Hub.cs
  test/Sentry.Tests/HubTests.cs
Labels: Performance Product

#910 Add useful contextual data to TransactionSamplingContext in ASP.NET Core integration
  CHANGELOG.md
  samples/Sentry.Samples.AspNetCore5.Mvc/Program.cs
  src/Sentry.AspNetCore/SamplingExtensions.cs
  src/Sentry.AspNetCore/SentryTracingMiddleware.cs
  src/Sentry/HubExtensions.cs
  src/Sentry/TransactionContext.cs
  test/Sentry.AspNetCore.Tests/SentryTracingMiddlewareTests.cs
Labels: Performance Product, enhancement
