Repository getsentry/sentry-dotnet, pull requests merged in 2021-09, with the labels that each got.

#1179 Fix SQLClient unplanned behaviors
  CHANGELOG.md
  src/Sentry.DiagnosticSource/Internals/DiagnosticSource/SentrySqlListener.cs
  src/Sentry/SpanTracer.cs
  test/Sentry.DiagnosticSource.Tests/DiagnosticsSentryOptionsExtensionsTests.cs
  test/Sentry.DiagnosticSource.Tests/Integration/SQLite/Database.cs
  test/Sentry.DiagnosticSource.Tests/Integration/SQLite/Item.cs
  test/Sentry.DiagnosticSource.Tests/Integration/SQLite/ItemsContext.cs
  test/Sentry.DiagnosticSource.Tests/Integration/SQLite/SentryDiagnosticListenerTests.cs
  test/Sentry.DiagnosticSource.Tests/Sentry.DiagnosticSource.Tests.csproj
  test/Sentry.DiagnosticSource.Tests/SentryEFCoreListenerTests.cs
  test/Sentry.DiagnosticSource.Tests/SentrySqlListenerTests.cs
  test/Sentry.Tests/Sentry.Tests.csproj
  test/Sentry.Tests/SpanTracerTests.cs
Labels: bug

#1183 Fix: braces from tag keys on DefaultSentryScopeStateProcessor.
  CHANGELOG.md
  src/Sentry/DefaultSentryScopeStateProcessor.cs
  test/Sentry.Tests/DefaultSentryScopeStateProcessorTests.cs
Labels: bug

#1188 Fix: Use fallback if RoutePattern is MVC.
  CHANGELOG.md
  src/Sentry.AspNetCore/Extensions/HttpContextExtensions.cs
  test/Sentry.AspNetCore.Tests/Extensions/HttpContextExtensionsTests.cs
Labels: bug, ASP.NET Core

#1201 Update README for NLog sample
  samples/Sentry.Samples.NLog/README.md
Labels: documentation

#1202 Update CONTRIBUTING.md, add file to solution
  CONTRIBUTING.md
  Sentry.sln
Labels: documentation

#1198 Add missing PathBase.
  CHANGELOG.md
  src/Sentry.AspNetCore/Extensions/HttpContextExtensions.cs
  test/Sentry.AspNetCore.Tests/Extensions/HttpContextExtensionsTests.cs
Labels: bug
