Repository getsentry/sentry-dotnet, pull requests merged in 2022-03, with the labels that each got.

#1509 Resolve System.Text.Json compatibility warning
  test/Sentry.DiagnosticSource.Tests/Sentry.DiagnosticSource.Tests.csproj
  test/Sentry.Tests/Sentry.Tests.csproj
Labels: Testing, Platform: .NET

#1510 Skip failing test on M1
  test/Sentry.Tests/Internals/ProcessInfoTests.cs
Labels: Testing

#1512 Fix typo
  CONTRIBUTING.md
Labels: documentation, Platform: .NET

#1543 fix infinite loop in SentryDatabaseLogging.UseBreadcrumbs
  CHANGELOG.md
  src/Sentry.EntityFramework/SentryDatabaseLogging.cs
Labels: bug

#1554 chore: wrap GetFromRuntimeInformation() in try-catch
  src/Sentry/PlatformAbstractions/RuntimeInfo.cs
Labels: bug
